#!/usr/bin/env node
// BEFORE RUNNING:
// ---------------
// 1. If not already done, enable the Google Sheets API
//    and check the quota for your project at
//    https://console.developers.google.com/apis/api/sheets
// 2. Install the Node.js client library by running
//    `npm install googleapis --save`

const {google} = require('googleapis');
const sheets = google.sheets('v4');
const path = require('path')
const fs = require('fs')

// credentials.json is a service credentials json. much easier than
// dealing with oauth tokens
function authorize(scopes) {
	const keyFile = "credentials.json"
	return new google.auth.GoogleAuth({ keyFile, scopes })
}

const SCOPES = [ "https://www.googleapis.com/auth/spreadsheets" ];

async function make_request(spreadsheetId)
{
	const auth = authorize(SCOPES);
	const range = "D2:I"
	const request = { spreadsheetId, auth, range };

	try {
		const response = (await sheets.spreadsheets.values.get(request)).data;
		console.log(JSON.stringify(response, null, 2));
	} catch (err) {
		console.error(err);
	}
}

function usage()
{
	const name = path.basename(process.argv[1])
	console.log("usage: %s [spreadsheet_id]", name)
	process.exit(0)
}

async function main () {
	if (process.argv.length !== 3)
		return usage()

	const spreadsheetId = process.argv[2]
	
	await make_request(spreadsheetId)
}

main();

